language: python
python:
  - "3.4"
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -e .
  - pip install coverage
# command to run tests
script: coverage run -m unittest discover -s tests -v && coverage report -m
