language: python
python:
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - pip install -e .
  - pip install coverage
# command to run tests
script: coverage run -m unittest discover -s tests -v && coverage report -m
